[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "code_style"
version = "v1.0.0"

[tool.hatch.build.targets.wheel]
include = ["code_style"]

[project.entry-points."pygments.styles"]
code = "code_style:CodeStyle"
